# These tools are used by Dockerfile.builder. Make sure that they're always
# included regardless of source code imports. Note that "required" deals in
# package names, whereas constraint/override names deal in project names.
# Specific versions of all tools listed here should have constraints to fix
# the versions we're using of them, unless otherwise noted.
required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc",
  "github.com/capsule8/protoc-gen-micro",

  # golint has no tags or releases. Since it does not generate any code and is
  # only used to validate code, leave it without a constraint.
  "github.com/golang/lint/golint",
]

# Use an override here instead of a constraint, because
# github.com/grpc-ecosystem/go-grpc-middleware has an explicit dependency on
# branch "master" for github.com/golang/protobuf.
# See https://github.com/grpc-ecosystem/go-grpc-middleware/issues/126
#[[override]]
#  name = "github.com/golang/protobuf"
#  version = "1.2.0"

#[[constraint]]
#  name = "github.com/grpc-ecosystem/grpc-gateway"
#  version = "1.4.1"

#[[constraint]]
#  name = "github.com/pseudomuto/protoc-gen-doc"
#  version = "1.1.0"

#[[constraint]]
#  name = "google.golang.org/grpc"
#  version = "=1.11.2"
